fixed feature type 1 - Point
DenysMoskalenko/vt2pbf pull request #1
Opened 2022-09-15 14:54 UTC by juloaiza

For feature type 1 (point) the module raise an error. Bug fixed

2022-09-15 16:47 UTC, DenysMoskalenko requested changes

2022-09-15 16:47 UTC, DenysMoskalenko commented on vt2pbf/service/feature.py
> +        raw_geometry = [raw_geometry] if self.feature_type == 1 else raw_geometry
According to typehint in this function raw_geometry must have a structure like "List[List[List[int]]]"
It means you cannot just wrap raw_geometry once more cause of feature_type.

I sure the problem should be resolved before this function, namely in add_geometry. Also add_geometry typehints must be changed for more basic structure to support Poin geometry

2022-09-15 16:48 UTC, DenysMoskalenko commented on vt2pbf/service/feature.py
> +        raw_geometry = [raw_geometry] if self.feature_type == 1 else raw_geometry
I u want u can make this changes and I will merge PR and update library version, if not - I will do it sometimes

2022-09-15 18:47 UTC, DenysMoskalenko commented
Look on you fork PR https://github.com/juloaiza/vt2pbf/pull/1

2022-09-16 08:40 UTC, DenysMoskalenko approved these changes

2022-09-16 08:40 UTC, merged

2022-09-16 17:34 UTC, juloaiza commented
Thank you!